### ISSUE TITLE
Termination

### ISSUE THREAD

**Issue by 0xastro** [ericps1/crts#13]
I have got a sudden error[1] when running any scenario on CORNET lab.

[1]sh
`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)`

**Comment by ericps1** [comment]
Hi, more information would be helpful. Is this error seen when executing crts_controller or crts_cognitive_radio? What is the output before this error e.g. does the crts_cognitive_radio receive the scenario parameters before this error occurs or is this literally the only output you're seeing?

That said, I logged into CORNET, did a fresh clone of the repo, and I'm seeing issues related to the UHD drivers when I try to run crts_cognitive_radio. I'm assuming something was updated on the CORNET servers which broke some of the calls we've used in the CRTS code. Perhaps this is the same issue you're seeing although I'm not seeing the same error signature as you. I'll look into updating the UHD API calls shortly.

**Comment by 0xastro** [comment]
the error seen when executing `crts_cognitive_radio` and I only see `**node parameters**` which are defined in scenario configuration file.[1]

```
linux; GNU C++ version 4.8.4; Boost_105400; UHD_003.008.004-0-g93011c14
--------------------------------------------------------------
-                    node parameters                         -
--------------------------------------------------------------
General Settings:
    Team name:                         Default
    Node type:                       Cognitive Radio
    Cognitive Radio type:      Extensible Cognitive Radio
    Server IP:                         192.168.1.55
Virtual Network Interface Settings:
    CRTS IP:                           10.0.0.2
    Target IP:                          10.0.0.3
    Traffic pattern:                   stream
    Average throughput:        2000000.00
Cognitive Engine Settings:
    Cognitive Engine:                  CE_PU_Markov_Chain_VER3
    CE timeout:                            200.00
Log/Report Settings:
    Physical layer rx log file:        _node_1_cognitive_radio_phy_rx
    Physical layer tx log file:        _node_1_cognitive_radio_phy_tx
    Network layer rx log file:        _node_1_cognitive_radio_net_rx
    Network layer tx log file:        _node_1_cognitive_radio_net_tx
    Generate octave logs:              0
Initial USRP Settings:
    Receive frequency:            8.62e+08
    Receive rate:                      1.00e+06
    Receive gain:                      15.00
    Transmit frequency:          8.33e+08
    Transmit rate:                     2.00e+06
    Transmit gain:                     25.00
Initial Liquid OFDM Settings
    Receive subcarriers:                 64
    Receive cyclic prefix length:    16
    Receive taper length:                4
    Transmit subcarriers:               64
    Transmit cyclic prefix length:  16
    Transmit taper length:              4
    Transmit soft gain:                  -12.00
    Transmit modulation:              bpsk
    Transmit CRC:                         crc32
    Transmit FEC0:                        h128
    Transmit FEC1:                         none
--------------------------------------------------------------
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

```

**Comment by 0xastro** [comment]
I tried to clone and recompile _crts_ and now it works fine.

**Comment by ericps1** [comment]
Yeah, my issue went away when I rebuilt on a different node. It looks like nodes 7001 and 7002 have the USRP X300 on them, I'm wondering if someone is messing around with the UHD software on these nodes. Anyways, not going to worry about this unless there's a problem on nodes with the typical setup.
